# Server Configuration
server.port=8081

# POSTGRESQL CONNECTION CLOUD SERVER
#spring.datasource.url=jdbc:postgresql://34.18.104.74:5432/postgres
spring.r2dbc.url=r2dbc:postgresql://34.18.104.74:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=Poclab_123#

#spring.datasource.username=postgres
#spring.datasource.password=Poclab_123#
#spring.datasource.driver-class-name=org.postgresql.Driver

# R2DBC POSTGRESQL CONNECTION LOCAL
# spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
# spring.r2dbc.username=ramansivanandi
# spring.r2dbc.password=postgresql

# R2DBC POSTGRESQL CONNECTION CLOUD SERVER
#spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
#spring.r2dbc.username=ramansivanandi
#spring.r2dbc.password=postgresql

# R2DBC Pool Settings
spring.r2dbc.pool.initial-size=2
spring.r2dbc.pool.max-size=10
spring.r2dbc.pool.max-idle-time=30m

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql.QUERY=DEBUG

# SpringDoc OpenAPI (Swagger)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
