-- =====================================================================
-- Quick Reset: Delete All Data and Reset Sequences
-- Simpler version - just deletes data and resets sequences
-- =====================================================================

-- Delete all data from tables (in reverse order of dependencies)
DELETE FROM ON_LOAD_SERVICE;
DELETE FROM WIDGET_ACTION;
DELETE FROM UI_DATA_SOURCE;
DELETE FROM WIDGET_RULE;
DELETE FROM WIDGET_PROPS;
DELETE FROM WIDGET;
DELETE FROM PAGE;
DELETE FROM CATEGORY;
DELETE FROM PRODUCT;

-- Reset sequences to start from 1
-- Oracle doesn't support RESTART, so we need to drop and recreate
DROP SEQUENCE SEQ_PRODUCT_ID;
DROP SEQUENCE SEQ_CATEGORY_ID;
DROP SEQUENCE SEQ_PAGE_ID;
DROP SEQUENCE SEQ_WIDGET_ID;
DROP SEQUENCE SEQ_PROP_ID;
DROP SEQUENCE SEQ_RULE_ID;
DROP SEQUENCE SEQ_DS_ID;
DROP SEQUENCE SEQ_ACTION_ID;
DROP SEQUENCE SEQ_ON_LOAD_SERVICE_ID;

-- Recreate sequences starting from 1
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATEGORY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAGE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_WIDGET_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROP_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RULE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DS_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACTION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ON_LOAD_SERVICE_ID START WITH 1 INCREMENT BY 1;

COMMIT;

-- Verification (optional)
-- SELECT 'Products: ' || COUNT(*) FROM PRODUCT
-- UNION ALL
-- SELECT 'Categories: ' || COUNT(*) FROM CATEGORY
-- UNION ALL
-- SELECT 'Pages: ' || COUNT(*) FROM PAGE
-- UNION ALL
-- SELECT 'Widgets: ' || COUNT(*) FROM WIDGET;

