-- =====================================================================
-- Oracle Database Schema for Dynamic UI Configuration
-- =====================================================================

-- Drop tables in reverse order of dependencies
DROP TABLE ON_LOAD_SERVICE CASCADE CONSTRAINTS;
DROP TABLE WIDGET_ACTION CASCADE CONSTRAINTS;
DROP TABLE UI_DATA_SOURCE CASCADE CONSTRAINTS;
DROP TABLE WIDGET_RULE CASCADE CONSTRAINTS;
DROP TABLE WIDGET_PROPS CASCADE CONSTRAINTS;
DROP TABLE WIDGET CASCADE CONSTRAINTS;
DROP TABLE PAGE CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;

-- Create PRODUCT table
CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(500)
);

-- Create CATEGORY table
CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CONSTRAINT FK_CATEGORY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE
);

-- Create PAGE table
CREATE TABLE PAGE (
    PAGE_ID NUMBER PRIMARY KEY,
    CATEGORY_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    ORDER_NO NUMBER NOT NULL,
    LAYOUT_TYPE VARCHAR2(20),
    COLUMNS_PER_ROW NUMBER,
    CONSTRAINT FK_PAGE_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) ON DELETE CASCADE
);

-- Create WIDGET table
CREATE TABLE WIDGET (
    WIDGET_ID NUMBER PRIMARY KEY,
    PAGE_ID NUMBER NOT NULL,
    PARENT_WIDGET_ID NUMBER,
    TYPE VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    LABEL VARCHAR2(200),
    ORDER_NO NUMBER NOT NULL,
    CONSTRAINT FK_WIDGET_PAGE FOREIGN KEY (PAGE_ID) REFERENCES PAGE(PAGE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_WIDGET_PARENT FOREIGN KEY (PARENT_WIDGET_ID) REFERENCES WIDGET(WIDGET_ID) ON DELETE CASCADE
);

-- Create WIDGET_PROPS table
CREATE TABLE WIDGET_PROPS (
    PROP_ID NUMBER PRIMARY KEY,
    WIDGET_ID NUMBER NOT NULL,
    PROP_KEY VARCHAR2(100) NOT NULL,
    PROP_VALUE VARCHAR2(500),
    CONSTRAINT FK_PROPS_WIDGET FOREIGN KEY (WIDGET_ID) REFERENCES WIDGET(WIDGET_ID) ON DELETE CASCADE
);

-- Create WIDGET_RULE table
CREATE TABLE WIDGET_RULE (
    RULE_ID NUMBER PRIMARY KEY,
    WIDGET_ID NUMBER NOT NULL,
    RULE_TYPE VARCHAR2(100) NOT NULL,
    RULE_EXPRESSION VARCHAR2(500),
    CONSTRAINT FK_RULE_WIDGET FOREIGN KEY (WIDGET_ID) REFERENCES WIDGET(WIDGET_ID) ON DELETE CASCADE
);

-- Create UI_DATA_SOURCE table
CREATE TABLE UI_DATA_SOURCE (
    DS_ID NUMBER PRIMARY KEY,
    WIDGET_ID NUMBER NOT NULL,
    SOURCE_TYPE VARCHAR2(50) NOT NULL,
    SOURCE_VALUE VARCHAR2(1000),
    CONSTRAINT FK_DATASOURCE_WIDGET FOREIGN KEY (WIDGET_ID) REFERENCES WIDGET(WIDGET_ID) ON DELETE CASCADE
);

-- Create WIDGET_ACTION table
CREATE TABLE WIDGET_ACTION (
    ACTION_ID NUMBER PRIMARY KEY,
    WIDGET_ID NUMBER NOT NULL,
    ACTION_NAME VARCHAR2(100) NOT NULL,
    ACTION_TYPE VARCHAR2(50) NOT NULL,
    TRIGGER_EVENT VARCHAR2(50) DEFAULT 'click',
    HTTP_METHOD VARCHAR2(10),
    ENDPOINT_URL VARCHAR2(1000),
    PAYLOAD_TEMPLATE CLOB,
    PAYLOAD_TYPE VARCHAR2(20) DEFAULT 'dynamic',
    HEADERS CLOB,
    QUERY_PARAMS CLOB,
    SUCCESS_HANDLER VARCHAR2(500),
    ERROR_HANDLER VARCHAR2(500),
    TIMEOUT_MS NUMBER DEFAULT 30000,
    ORDER_NO NUMBER DEFAULT 1,
    IS_ENABLED CHAR(1) DEFAULT 'Y',
    CONDITION_EXPRESSION VARCHAR2(500),
    CONSTRAINT FK_ACTION_WIDGET FOREIGN KEY (WIDGET_ID) REFERENCES WIDGET(WIDGET_ID) ON DELETE CASCADE
);

-- Create ON_LOAD_SERVICE table
CREATE TABLE ON_LOAD_SERVICE (
    ON_LOAD_SERVICE_ID NUMBER PRIMARY KEY,
    PAGE_ID NUMBER NOT NULL,
    SERVICE_ID VARCHAR2(100) NOT NULL,
    API VARCHAR2(1000) NOT NULL,
    HTTP_METHOD VARCHAR2(10) NOT NULL,
    PAYLOAD CLOB,
    HEADERS CLOB,
    SERVICE_IDENTIFIER VARCHAR2(100),
    ON_SUCCESS VARCHAR2(500),
    ON_FAILURE VARCHAR2(500),
    CONSTRAINT FK_ONLOAD_PAGE FOREIGN KEY (PAGE_ID) REFERENCES PAGE(PAGE_ID) ON DELETE CASCADE
);

-- Create sequences for auto-increment IDs
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATEGORY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAGE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_WIDGET_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROP_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RULE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DS_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACTION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ON_LOAD_SERVICE_ID START WITH 1 INCREMENT BY 1;

-- Create indexes for better performance
CREATE INDEX IDX_CATEGORY_PRODUCT_ID ON CATEGORY(PRODUCT_ID);
CREATE INDEX IDX_PAGE_CATEGORY_ID ON PAGE(CATEGORY_ID);
CREATE INDEX IDX_WIDGET_PAGE_ID ON WIDGET(PAGE_ID);
CREATE INDEX IDX_PROPS_WIDGET_ID ON WIDGET_PROPS(WIDGET_ID);
CREATE INDEX IDX_RULE_WIDGET_ID ON WIDGET_RULE(WIDGET_ID);
CREATE INDEX IDX_DATASOURCE_WIDGET_ID ON UI_DATA_SOURCE(WIDGET_ID);
CREATE INDEX IDX_ACTION_WIDGET_ID ON WIDGET_ACTION(WIDGET_ID);
CREATE INDEX IDX_ONLOAD_PAGE_ID ON ON_LOAD_SERVICE(PAGE_ID);

COMMIT;

